# Generated by Django 3.2.7 on 2021-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prénom', models.CharField(max_length=200)),
                ('vacciné', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('groupe', models.IntegerField()),
                ('avisé', models.CharField(max_length=200)),
                ('nom_tuteur', models.CharField(max_length=200)),
                ('prénom_tuteur', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('courriel', models.CharField(max_length=200)),
                ('langue', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nom', 'prénom'),
            },
        ),
    ]
