# Generated by Django 3.2.7 on 2021-10-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractrow',
            name='sex',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
